[package]
name = "eddie"
version = "0.1.0"
authors = ["Ilia Schelokov <thaumant@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"
distance = "0.4"
strsim = "0.9"
rand = "0.7"

[[bench]]
name = "damerau_levenshtein"
harness = false

[[bench]]
name = "levenshtein"
harness = false

[[bench]]
name = "jaro"
harness = false